# Multiclass classifcation

In [1]:
import numpy
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [2]:
numpy.random.seed(7)

In [3]:
data = pd.read_csv("iris.csv")
# data converted into the values. that means list
data = data.values
X = data[:,0:4].astype(float)
y= data[:,4]

In [4]:
# Encode the input
# one hot encoding
encoder = LabelEncoder()
encoder.fit(y)
encoder_y  = encoder.transform(y)
encoder_y # here we can see only the encoding. but we need putput inthe form onehot encoding.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
# one hot encoding
dummy_y = np_utils.to_categorical(encoder_y)
dummy_y[0:4]

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [6]:
# baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(4, input_dim=4,activation='relu'))
    model.add(Dense(3, activation='softmax'))
    # model compile
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [7]:
estimator = KerasClassifier(build_fn = baseline_model, epochs=10, batch_size=5, verbose=0)

In [12]:
kfold = KFold(n_splits=10, shuffle= True, random_state= 7)
result = cross_val_score(estimator, X, dummy_y, cv = kfold)
result

array([ 0.20000001,  0.60000001,  0.4       ,  0.40000001,  0.73333333,
        0.73333333,  0.73333333,  0.73333333,  0.13333334,  0.42857143])

In [14]:
result.mean()*100

50.95238127169155

In [15]:
result.std()*100

21.826983957343529